### PR TITLE
FIX #13

### LINKED ISSUE #13: Can not get data when type TIME metrics. e.g. sessionDuration
When I get data of metric whose type is TIME, e.g. sessionDuration, GA API returns double values but this plug-in cast 'timestamp' type
https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessionduration

### PR DESCRIPTION
**Pull request by kazuya030**
when data type is “TIME”, this will return double value

### CODE REVIEW

**Comment by kazuya030** [comment]
I read the result failed, but cannot understand the reason.
I think the point is that the test contains "ga:sessionDuration" in metrics.

I'd appreciate it if you could advice this.

**Comment by uu59** [comment]
As we discussed on Twitter, TIME data type should be HH:MM:SS format as documented, but actual data is just a number.
https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?hl=en#metrictype
https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessionduration

We should investigate other TIME columns data and format.
If all of them are the number, this PR changes is good 👍 
I'll check them later.

**Comment by uu59** [comment]
Sorry for late.

All dataType: TIME columns are the below, grabbed them with [metadata API](https://developers.google.com/analytics/devguides/reporting/metadata/v3/reference/metadata/columns/list).
My test account has no value for them. I checked Google official document for each column information.
- (double) [ga:sessionDuration](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessionduration) Total duration (in seconds) of users' sessions.
- (seems double) [ga:timeOnSite](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_timeonsite) Deprecated
- (double) [ga:avgSessionDuration](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_avgsessionduration) The average duration (in seconds) of users' sessions.
- (seems double) [ga:avgTimeOnSite](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_avgtimeonsite) Deprecated
- (double) [ga:timeOnPage](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=page_tracking&jump=ga_timeonpage) Time (in seconds) users spent on a particular page
- (double) [ga:avgTimeOnPage](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=page_tracking&jump=ga_avgtimeonpage) `ga:timeOnPage / (ga:pageviews - ga:exits)`
- (seems double) [ga:searchDuration](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=internal_search&jump=ga_searchduration) The session duration
- (double) [ga:avgSearchDuration](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=internal_search&jump=ga_avgsearchduration) The average time (in seconds)
- (double) [ga:timeOnScreen](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=page_tracking&jump=ga_timeonpage) Time (in seconds) users spent on a particular page
- (double) [ga:avgScreenviewDuration](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=page_tracking&jump=ga_avgtimeonpage) `ga:timeOnPage / (ga:pageviews - ga:exits)`
- (seems double) [ga:cohortSessionDurationPerUser](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=lifetime_value_and_cohorts&jump=ga_cohortsessiondurationperuser) Session duration per user for a cohort
- (double) [ga:cohortSessionDurationPerUserWithLifetimeCriteria](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=lifetime_value_and_cohorts&jump=ga_cohortsessiondurationperuserwithlifetimecriteria) `ga:sessionDuration / ga:cohortTotalUsersWithLifetimeCriteria`

ga:TimeOnSite and ga:avgTimeOnSite aren't described detail on their document, but seems double because other all TIME columns are so.

**Comment by uu59** [comment]
This PR is merged at #15, and released a new version v0.1.8 including this changes.
Thank you for your cooperation!

**Pull request merged**
